export {default as Navbar} from './Navbar/Navbar';
export {default as Products} from './Products/Products';
export {default as DetailsP} from './Products/DetailsP';
export {default as AddProduct} from './Store/Store Products/AddProducts';
export {default as Cart} from './Cart/Cart';
export {default as Error} from './Error/Error';
export {default as Checkout} from './Checkout/Checkout';
export {default as Login} from './Login/Login';
export {default as Store} from './Store/Store Profile/Store';
export {default as Favorite} from './Favorite/Favorite';
export {default as Profile} from './Profile/Profile';
export {default as Orders} from './Orders/Orders';
